cmake_minimum_required(VERSION  3.20)

project(QtWidgetAppsCollection)


add_subdirectory(Date_Timer)
add_subdirectory(Convertor)
add_subdirectory(Instrument_Dash_Board)
add_subdirectory(QtVulkanCubes)
add_subdirectory(SimpleWidget)
add_subdirectory(MultiThreading_DiceGame)
add_subdirectory(PainterBasics)
add_subdirectory(QtGuiCalculator)
